strictPeerDependencies: false
sideEffectsCache: false
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - "@cyco130/eslint-config"

packages:
  - packages/*
  - ci

allowBuilds:
  esbuild: true
  unrs-resolver: true
